name: AdvancedPlHide
depend:
  - ProtocolLib
version: @version@
description: @description@
authors:
  - BlueTree242
main: tk.bluetree242.advancedplhide.spigot.AdvancedPlHideSpigot

commands:
  advancedplhide:
    aliases: [aph, plhide, ph]